name: portofolio
description: A portofolio of apps.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  args: ^2.5.0
  flutter:
    sdk: flutter
  go_router: ^14.2.6
  grinder: ^0.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^6.0.0

flutter:
  uses-material-design: true
