name: portofolio
description: Portofolio app.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  intl: any
  transparent_image: ^2.0.1

dev_dependencies:
  design_patterns:
    path: ../design_patterns
  drawing:
    path: ../drawing
  flutter_test:
    sdk: flutter
  gorouter:
    path: ../gorouter
  material_3_demo:
    path: ../material_3_demo
  rally:
    path: ../rally
  widgetbook_workspace:
    path: ../widgetbook_demo/widgetbook
  riverpod_demo:
    path: ../riverpod_demo
  scrolling: 
    path: ../scrolling

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
